version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/daata/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    build: .
    restart: always
    image: clean-node-api
    links:
      - mongo
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    ports:
      - "5000:5000"
